// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV4RifUshGtpKrp1rBRS-lanyahf24Ap4',
    appId: '1:682436232960:android:b9171486b29b402dac95e5',
    messagingSenderId: '682436232960',
    projectId: 'capstone-app-654fe',
    storageBucket: 'capstone-app-654fe.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGje_3rFfqzR3lhXBWx9uTTXJ8AGoYlw',
    appId: '1:682436232960:ios:c3ca78a4b191f60dac95e5',
    messagingSenderId: '682436232960',
    projectId: 'capstone-app-654fe',
    storageBucket: 'capstone-app-654fe.firebasestorage.app',
    androidClientId: '682436232960-qm0nkrn30pr3u7759ijbnuvrv2lldkmn.apps.googleusercontent.com',
    iosClientId: '682436232960-j50df9vr88dln3j3hivgsu4am3b3fuba.apps.googleusercontent.com',
    iosBundleId: 'com.g3.rehomeit',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pQ13t5XMXYwmbHraMeET_Irx4Uo4WTU',
    appId: '1:682436232960:web:decc669d32f64e89ac95e5',
    messagingSenderId: '682436232960',
    projectId: 'capstone-app-654fe',
    authDomain: 'capstone-app-654fe.firebaseapp.com',
    storageBucket: 'capstone-app-654fe.firebasestorage.app',
    measurementId: 'G-ZBHRG6ZRJT',
  );
}
